springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG

spring.datasource.url=>${DATABASE_URL}
#spring.datasource.url=jdbc:postgresql://localhost:5432/kotospring
#spring.datasource.username=kotospring
#spring.datasource.password=kotospring
#
