spring.application.name=server
spring.profiles.default=dev
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.batch_versioned_data=true
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
