spring.application.name=client
spring.shell.script.enabled=true
spring.shell.interactive.enabled=true
spring.main.web-application-type=none
logging.level.root=OFF
spring.main.banner-mode=off
server.api.base-url=http://localhost:8080